# Configure colors to work with tmux
if [[ $COLORTERM == "gnome-terminal" ]]; then
    export TERM="xterm-256color"
fi
export ZSH_TMUX_AUTOSTART=true

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git tmux composer docker docker-compose)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias phptags="ctags -R --PHP-kinds=+cf"
alias phpvendortags="ctags -R --PHP-kinds=+cf -f tags.vendors vendor"

# PHP XDebug support
# Usually XDebug should be disabled by default to have a better performance
export XDEBUG_CONFIG=""
alias php-debug='php -d "zend_extension=xdebug.so" \
    -d "xdebug.max_nesting_level=250" \
    -d "xdebug.remote_enable=on" \
    -d "xdebug.remote_handler=dbgp" \
    -d "xdebug.remote_port=9001"'
alias sfserverstart="sudo php5enmod xdebug; app/console server:start; sudo php5dismod xdebug"
alias sfserverstop="app/console server:stop"

# rbenv
if [[ -d "$HOME/.rbenv" ]]; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi

# Use binary files from composer
if [[ -d ~/.composer/vendor/bin ]]; then
    export PATH=~/.composer/vendor/bin:$PATH
fi

# Use binary files from GoLang package
if [[ -d /usr/local/go/bin ]]; then
    export GOPATH=$HOME/.golang
    export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
fi

# Source fzf configuration
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Disable XON/XOFF flow control
stty -ixon

# Use git-radar if available on prompt (robbyrussell theme)
if [[ -f ~/.git-radar/git-radar ]]; then
    export GIT_RADAR_COLOR_BRANCH="$fg_bold[red]"
    PROMPT='${ret_status}%{$fg_bold[green]%}%p %{$fg[cyan]%}%c$(~/.git-radar/git-radar --zsh)%{$fg_bold[blue]%} % %{$reset_color%}'
fi

# added by travis gem
[ -f /home/ellis/.travis/travis.sh ] && source /home/ellis/.travis/travis.sh
